USE [QACOP]
GO

SELECT DISTINCT
(SELECT COUNT (STATUS) from SP_Utility_DQ_OUTPUT WHERE SP_Utility_DQ_OUTPUT.STATUS = 'FAILED') AS FAILED,
(SELECT COUNT(STATUS)  from SP_Utility_DQ_OUTPUT WHERE SP_Utility_DQ_OUTPUT.STATUS = 'PASSED') AS PASSED,
(SELECT COUNT(STATUS)  from SP_Utility_DQ_OUTPUT) AS TOTAL FROM SP_Utility_DQ_OUTPUT

GO
